version: "3.9"

volumes:
  postgres_data:
    driver: local

services:
  gamma-postgres:
    image: postgres:latest
    container_name: gamma-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vnuser
      POSTGRES_PASSWORD: vnpass

  gamma-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: gamma-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
